name: Metrics

on:
    schedule: # 安排每日更新
        - cron: "* */24 * * *"
    workflow_dispatch: # (可选）手动运行工作流程
    # (可选）在master/main推送时运行工作流
    push: { branches: ["master", "main"] }

jobs:
    github-metrics:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
        - uses: lowlighter/metrics@latest
        with:
            token: ${{ secrets.METRICS_TOKEN }}
