name: Snake Contrib

on:
  schedule: # 每24小时自动运行一次
    - cron: "* */24 * * *"

  # 允许随时手动运行作业
  workflow_dispatch:

  # 在主分支上的每次推送上运行
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # 从 GitHub 用户(<github_user_name>)贡献图生成贪吃蛇游戏,输出 <svg_out_path>SVG 动画
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 将 <build_dir> 的内容推送到一个分支
      # 内容将在 https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> 或作为 github 页面提供
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}